package hu.logcontrol.mobilflexandroid.enums;

public enum ViewEnums {
    MAIN_ACTIVITY,
    LOGIN_ACTIVITY,
    WEBVIEW_ACTIVITY,
    SETTINSG_ACTIVITY,
    APPLICATIONS_ACTIVITY,

    USERNAME_PASSWORD_FRAGMENT,
    PINCODE_FRAGMENT,
    RFID_FRAGMENT,
    BARCODE_FRAGMENT
}
